### ISSUE TITLE
IllegalStateException 

### ISSUE THREAD

**Issue by alexodus** [googlesamples/identity-toolkit-android#20]
I received this crash report from a Samsung GT-i9505 Galaxy S4:

```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
    at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1343)
    at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1361)
    at android.app.BackStackRecord.commitInternal(BackStackRecord.java:728)
    at android.app.BackStackRecord.commit(BackStackRecord.java:704)
    at android.app.DialogFragment.dismissInternal(DialogFragment.java:292)
    at android.app.DialogFragment.dismiss(DialogFragment.java:258)
    at com.google.identitytoolkit.ui.DefaultUiManager.dismiss(DefaultUiManager.java:108)
    at com.google.identitytoolkit.GitkitClient.setLoggedIn(GitkitClient.java:425)
    at com.google.identitytoolkit.GitkitClient.handleVerifyResponse(GitkitClient.java:420)
    at com.google.identitytoolkit.GitkitClient.access$1000(GitkitClient.java:90)
    at com.google.identitytoolkit.GitkitClient$4.call(GitkitClient.java:376)
    at com.google.identitytoolkit.GitkitClient$4.call(GitkitClient.java:373)
    at com.google.identitytoolkit.executor.ProgressRequestExecutor$2.onPostExecute(ProgressRequestExecutor.java:95)
    at android.os.AsyncTask.finish(AsyncTask.java:632)
    at android.os.AsyncTask.access$600(AsyncTask.java:177)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:5951)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
```

I'm using this libs:
- identitytoolkit-api11.aar
- identitytoolkit_fbv4.jar

**Comment by alexodus** [comment]
yesterday I received the same crash from an HTC One M8

**Comment by XiaoxiongLu** [comment]
Hi alexodus, sorry for the late reply. Could you tell me more specific at which step you received the crash? Thanks

**Comment by alexodus** [comment]
I haven't any other information: this is a crash report (via ACRA) remotely sent

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
