### ISSUE TITLE
GoogleIdpClient: Unrecoverable auth exception: Unknown

### ISSUE THREAD

**Issue by eliotstock** [googlesamples/identity-toolkit-android#21]
I followed the Quick-start instructions to the letter, but still got this exception when selecting one of my Google accounts on the device:

03-28 16:02:52.728 18683-19170/com.google.identitytoolkit.demo E/GoogleIdpClient: Unrecoverable auth exception: Unknown
com.google.android.gms.auth.GoogleAuthException: Unknown
  at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source)
  at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source)
  at com.google.identitytoolkit.idp.google.GoogleIdpClient$1.call(GoogleIdpClient.java:126)
  at com.google.identitytoolkit.idp.google.GoogleIdpClient$1.call(GoogleIdpClient.java:120)
  at com.google.identitytoolkit.executor.ProgressRequestExecutor$2.doInBackground(ProgressRequestExecutor.java:84)
  at com.google.identitytoolkit.executor.ProgressRequestExecutor$2.doInBackground(ProgressRequestExecutor.java:71)
  at android.os.AsyncTask$2.call(AsyncTask.java:295)
  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
  at java.lang.Thread.run(Thread.java:818)

Yes, I checked SO first. Yes, there's a question there on this. No, there's no answer there yet.

http://stackoverflow.com/questions/30888646/identity-toolkit-api-for-android

At the very least, GoogleAuthUtil should offer a more helpful error message.

**Comment by alexxsanchezm** [comment]
I think one solution may be implement an GoogleIdpClient instance and there add a callback which actually listen the Transient Error.

I would be happy if some one shows up how to get an instance of GoogleIdpClient.

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
