### ISSUE TITLE
android.view.WindowManager$BadTokenException

### ISSUE THREAD

**Issue by alexodus** [googlesamples/identity-toolkit-android#23]
I received this crash report from a Samsung Galaxy Grand Neo Plus (Android 4.4.4):

```
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@42713748 is not valid; is your activity running?
    at android.view.ViewRootImpl.setView(ViewRootImpl.java:591)
    at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:259)
    at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
    at android.app.Dialog.show(Dialog.java:286)
    at com.google.identitytoolkit.executor.ProgressRequestExecutor$2.onPreExecute(ProgressRequestExecutor.java:77)
    at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:587)
    at android.os.AsyncTask.execute(AsyncTask.java:535)
    at com.google.identitytoolkit.executor.ProgressRequestExecutor.asyncExecute(ProgressRequestExecutor.java:55)
    at com.google.identitytoolkit.executor.ProgressRequestExecutor.asyncExecute(ProgressRequestExecutor.java:50)
    at com.google.identitytoolkit.idp.google.GoogleIdpClient.getAccessTokenAndVerify(GoogleIdpClient.java:120)
    at com.google.identitytoolkit.idp.google.GoogleIdpClient.signIn(GoogleIdpClient.java:90)
    at com.google.identitytoolkit.GitkitClient$3.call(GitkitClient.java:359)
    at com.google.identitytoolkit.GitkitClient$3.call(GitkitClient.java:346)
    at com.google.identitytoolkit.executor.ProgressRequestExecutor$2.onPostExecute(ProgressRequestExecutor.java:95)
    at android.os.AsyncTask.finish(AsyncTask.java:632)
    at android.os.AsyncTask.access$600(AsyncTask.java:177)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5584)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
