### ISSUE TITLE
App Crash on Start Sign in

### ISSUE THREAD

**Issue by deepakbhatia** [googlesamples/identity-toolkit-android#6]
I am getting error when I am running the DEMO on MOTO G KitKat.

The error:

11-27 15:02:37.472    2863-2863/com.optimalcities.sharetravel E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.optimalcities.sharetravel, PID: 2863
    java.lang.NoClassDefFoundError: com.google.identitytoolkit.R$bool
            at com.google.identitytoolkit.ui.Page.forcePortraitIfNecessary(Page.java:113)
            at com.google.identitytoolkit.ui.Page.onCreateDialog(Page.java:72)
            at com.google.identitytoolkit.ui.StartSignInPage.onCreateDialog(StartSignInPage.java:27)
            at android.support.v4.app.DialogFragment.getLayoutInflater(DialogFragment.java:307)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:947)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1126)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:739)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1489)
            at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:454)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5086)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)

In the Demo, the class extends "FragmentActivity" instead of just "Activity", as with "Activity", the app crashes on start up, with message that the class needs to extend FragmentActivity.

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
